/* MINDFAX OPS chat - fluxo hibrido (doc 22) + captura de contato. Worker seguro. */
(function () {
  if (window.__MINDFAX_WIDGET__) return;
  window.__MINDFAX_WIDGET__ = true;
  var CHAT_URL = "https://mindfax-chat.iamediafactory-studio.workers.dev";
  var BOT = "t.me/mindfax_ops_bot", WA = "5561996138513", EM = "iamediafactory.studio@gmail.com";
  var GREETING = "👋 Welcome to MINDFAX OPS. We automate repetitive work for agencies.\n\nPlease choose your language / escolha o idioma / elige el idioma:";
  var LANG_BTNS = ["🇺🇸 English", "🇪🇸 Español", "🇧🇷 Português"];
  var CSS = ".mfx-chat-fab{position:fixed;right:22px;bottom:22px;z-index:9999;width:60px;height:60px;border-radius:50%;border:none;cursor:pointer;background:radial-gradient(circle at 30% 30%,#65e3c2,#1f9c6e);box-shadow:0 8px 24px rgba(0,0,0,.35);display:flex;align-items:center;justify-content:center}.mfx-chat-fab svg{width:30px;height:30px;fill:#06231a}.mfx-chat-panel{position:fixed;right:22px;bottom:92px;z-index:9999;width:360px;max-width:calc(100vw - 40px);height:min(480px,80vh);display:none;flex-direction:column;background:#0b1214;border:1px solid #1e2a2e;border-radius:16px;overflow:hidden}.mfx-chat-panel.open{display:flex}.mfx-chat-head{display:flex;align-items:center;gap:10px;padding:14px 16px;background:#0f1a1c;border-bottom:1px solid #1e2a2e}.mfx-chat-head .dot{width:9px;height:9px;border-radius:50%;background:#4fd1a5}.mfx-chat-head b{font-size:14px;color:#e8f4ee}.mfx-chat-head .sub{display:block;font-size:11px;color:#7f9a8d}.mfx-log{flex:1;overflow-y:auto;padding:14px 14px 6px;display:flex;flex-direction:column;gap:8px;font-size:13.5px}.mfx-b{max-width:82%;padding:9px 12px;border-radius:12px;line-height:1.45;white-space:pre-wrap}.mfx-b.ai{background:#14211d;border:1px solid #1f332b;color:#cfdfd7;align-self:flex-start}.mfx-b.you{background:#183a2e;color:#e8f4ee;align-self:flex-end}.mfx-b.ai b{color:#5ee0be}.mfx-typing{color:#5c7367;font-size:12px;padding:0 14px}.mfx-qr{display:flex;flex-wrap:wrap;gap:7px;padding:2px 0 8px}.mfx-qb{background:#13241f;border:1px solid #1f4333;color:#d7efe4;border-radius:999px;padding:7px 13px;font-size:12.5px;cursor:pointer}.mfx-bar{display:flex;gap:8px;padding:10px;border-top:1px solid #1e2a2e;background:#0d1517}.mfx-bar input{flex:1;background:#162226;border:1px solid #22333a;border-radius:10px;color:#e8f4ee;padding:9px 12px;font-size:13px;outline:none}.mfx-bar button{background:radial-gradient(circle at 30% 30%,#5ee0be,#1f9c6e);border:none;color:#03180f;font-weight:700;border-radius:10px;padding:0 16px;cursor:pointer;font-size:13px}.mfx-channels{display:flex;flex-direction:column;gap:8px;padding:10px 14px;border-top:1px solid #1e2a2e;background:#0d1517}.mfx-channels .tl{font-size:11px;color:#7f9a8d;text-align:center}.mfx-channel{display:flex;align-items:center;gap:9px;background:#14211d;border:1px solid #1f332b;border-radius:10px;padding:10px 12px;color:#e8f4ee;font-size:13px;cursor:pointer;text-align:left;width:100%}.mfx-channel span{flex:1}.mfx-note{font-size:10.5px;color:#5c7367;text-align:center;padding:6px}.mfx-note a{color:#4fd1a5;text-decoration:none;margin:0 3px}.mfx-hero{padding:8px 16px;background:radial-gradient(300px 60px at 50% 0%,rgba(79,209,165,.18),transparent 75%);font-size:13.5px;color:#e8f4ee}";
  var s = document.createElement("style"); s.textContent = CSS; document.head.appendChild(s);
  var fab = document.createElement("button"); fab.className = "mfx-chat-fab"; fab.setAttribute("aria-label", "Chat");
  fab.innerHTML = '<svg viewBox="0 0 24 24"><path d="M12 3C7 3 3 7.03 3 12c0 2 .7 3.8 1.9 5.2L3 21l4-1.5c1.3.7 2.8 1 4 1 5 0 9-4 9-8.5S17 3 12 3z"/></svg>';
  document.body.appendChild(fab);
  var pan = document.createElement("div"); pan.className = "mfx-chat-panel";
  pan.innerHTML = '<div class="mfx-chat-head"><span class="dot"></span><span><b>MINDFAX OPS</b><span class="sub">AI assistant · online</span></span></div>' +
    '<div class="mfx-hero">Chat with us 👇</div>' +
    '<div class="mfx-log" id="mfxLog"></div>' +
    '<div class="mfx-bar"><input id="mfxInput" placeholder="Type your message…" aria-label="Message"/><button id="mfxSend">Send</button></div>' +
    '<div class="mfx-note">Prefer another channel? <a href="https://' + BOT + '" target="_blank" rel="noopener">Telegram</a> · <a href="https://wa.me/' + WA + '" target="_blank" rel="noopener">WhatsApp</a> · <a href="mailto:' + EM + '">Email</a></div>';
  document.body.appendChild(pan);
  var log = document.getElementById("mfxLog"), input = document.getElementById("mfxInput"), send = document.getElementById("mfxSend");
  var history = [], language = "", step = "language", greetingShown = false;
  function esc(t) { return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
  function pushHtml(h) { var d = document.createElement("div"); d.className = "mfx-b ai"; d.innerHTML = h; log.appendChild(d); log.scrollTop = log.scrollHeight; }
  function push(role, text) { var d = document.createElement("div"); d.className = "mfx-b " + (role === "assistant" ? "ai" : "you"); d.innerHTML = esc(text).replace(/\n/g, "<br>"); log.appendChild(d); log.scrollTop = log.scrollHeight; }
  function buf() { var d = document.createElement("div"); d.className = "mfx-typing"; d.textContent = "…"; log.appendChild(d); log.scrollTop = log.scrollHeight; return d; }
  function renderButtons(btns, s2) { if (!btns || !btns.length) return; var q = document.createElement("div"); q.className = "mfx-qr"; btns.forEach(function (b) { var t = String(b || "").toLowerCase(), L = /^abrir|^abra|^abre|^open|^apert/.test(t), el = document.createElement("button"); el.className = "mfx-qb"; el.textContent = b; el.addEventListener("click", function () { if (L) { var mm = encodeURIComponent("Hi MINDFAX - chatted on site"); if (t.indexOf("telegram") >= 0) { window.open("https://" + BOT + "?text=" + mm, "_blank"); return; } if (t.indexOf("whatsapp") >= 0) { window.open("https://wa.me/" + WA + "?text=" + mm, "_blank"); return; } if (t.indexOf("email") >= 0 || t.indexOf("correo") >= 0) { window.open("mailto:" + EM + "?subject=Chat%20MINDFAX"); return; } } sendText(b, s2); }); q.appendChild(el); }); log.appendChild(q); log.scrollTop = log.scrollHeight; }
  function fallbackChannels(txt) { var c = document.createElement("div"); c.className = "mfx-channels"; c.innerHTML = '<div class="tl">Prefer to continue on another channel?</div><button class="mfx-channel" data-c="t"><span>💬 Telegram</span></button><button class="mfx-channel" data-c="w"><span>💬 WhatsApp</span></button><button class="mfx-channel" data-c="e"><span>📧 Email</span></button>'; log.appendChild(c); log.scrollTop = log.scrollHeight; c.addEventListener("click", function (e) { var b = e.target.closest(".mfx-channel"); if (!b) return; var m = encodeURIComponent("MINDFAX OPS: " + txt); var u = b.getAttribute("data-c") === "t" ? "https://" + BOT + "?text=" + m : b.getAttribute("data-c") === "w" ? "https://wa.me/" + WA + "?text=" + m : "mailto:" + EM + "?subject=" + encodeURIComponent("MINDFAX OPS") + "&body=" + m; window.open(u, "_blank"); }); }
  async function sendText(txt, stepToSend) { txt = (txt || "").trim(); if (!txt) return; push("user", txt); history.push({ role: "user", text: txt }); var ty = buf(); if (stepToSend === undefined) stepToSend = step; var curStep = step; try { var r = await fetch(CHAT_URL, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: txt, history: history.slice(0, -1), step: stepToSend, language: language }) }); var j = await r.json(); ty.remove(); if (j.ok) { if (j.language && stepToSend === "language") language = j.language; if (j.step) curStep = j.step; pushHtml(esc(j.reply || "").replace(/\n/g, "<br>")); history.push({ role: "assistant", text: j.reply || "" }); renderButtons(j.bottons, j.botStep || curStep); step = curStep; if (language) { var cl = log.parentElement.querySelector(".mfx-channels"); if (cl) cl.remove(); } } else { push("assistant", "Couldn't reply right now. Prefer to continue on one of the channels below:"); fallbackChannels(txt); } } catch (err) { ty.remove(); push("assistant", "Having some instability here. I can help you on one of these channels:"); fallbackChannels(txt); } }
  function ask() { var txt = (input.value || "").trim(); if (!txt) { input.focus(); return; } input.value = ""; sendText(txt); }
  fab.addEventListener("click", function () { pan.classList.toggle("open"); if (pan.classList.contains("open") && !greetingShown) { greetingShown = true; step = "language"; pushHtml(esc(GREETING).replace(/\n/g, "<br>")); var q = document.createElement("div"); q.className = "mfx-qr"; LANG_BTNS.forEach(function (b) { var el = document.createElement("button"); el.className = "mfx-qb"; el.textContent = b; el.addEventListener("click", function () { sendText(b, "language"); }); q.appendChild(el); }); log.appendChild(q); log.scrollTop = log.scrollHeight; setTimeout(function () { input.focus(); }, 200); } });
  send.addEventListener("click", ask);
  input.addEventListener("keydown", function (e) { if (e.key === "Enter") ask(); });
})();
