/* MINDFAX OPS chat - fluxo hibrido + captura de contato. Worker seguro. */
(function () {
  if (window.__MINDFAX_WIDGET__) return;
  window.__MINDFAX_WIDGET__ = true;
  var C = "https://mindfax-chat.iamediafactory-studio.workers.dev";
  var B = "t.me/mindfax_ops_bot", W = "5561996138513", E = "iamediafactory.studio@gmail.com";
  var GREETING = "👋 Welcome to MINDFAX OPS. We automate repetitive work.\n\nLanguage / idioma / idioma:";
  var LB = ["🇺🇸 English", "🇪🇸 Español", "🇧🇷 Português"];
  var CSS = ".mfx-chat-fab{position:fixed;right:22px;bottom:22px;z-index:9999;width:60px;height:60px;border-radius:50%;border:none;cursor:pointer;background:radial-gradient(circle at 30% 30%,#65e3c2,#1f9c6e);display:flex;align-items:center;justify-content:center}.mfx-chat-panel{position:fixed;right:22px;bottom:92px;z-index:9999;width:360px;max-width:calc(100vw - 40px);height:min(480px,80vh);display:none;flex-direction:column;background:#0b1214;border:1px solid #1e2a2e;border-radius:16px;overflow:hidden}.mfx-chat-panel.open{display:flex}.mfx-chat-head{display:flex;align-items:center;gap:10px;padding:12px 14px;background:#0f1a1c;border-bottom:1px solid #1e2a2e}.mfx-chat-head .dot{width:9px;height:9px;border-radius:50%;background:#4fd1a5}.mfx-chat-head b{font-size:14px;color:#e8f4ee}.mfx-chat-head .sub{display:block;font-size:11px;color:#7f9a8d}.mfx-log{flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:8px;font-size:13.5px}.mfx-b{max-width:82%;padding:9px 12px;border-radius:12px;line-height:1.45;white-space:pre-wrap}.mfx-b.ai{background:#14211d;border:1px solid #1f332b;color:#cfdfd7;align-self:flex-start}.mfx-b.you{background:#183a2e;color:#e8f4ee;align-self:flex-end}.mfx-typing{color:#5c7367;font-size:12px}.mfx-qr{display:flex;flex-wrap:wrap;gap:7px}.mfx-qb{background:#13241f;border:1px solid #1f4333;color:#d7efe4;border-radius:999px;padding:7px 13px;font-size:12.5px;cursor:pointer}.mfx-bar{display:flex;gap:8px;padding:10px;border-top:1px solid #1e2a2e;background:#0d1517}.mfx-bar input{flex:1;background:#162226;border:1px solid #22333a;border-radius:10px;color:#e8f4ee;padding:9px 12px;font-size:13px;outline:none}.mfx-bar button{background:radial-gradient(circle at 30% 30%,#5ee0be,#1f9c6e);border:none;color:#03180f;font-weight:700;border-radius:10px;padding:0 16px;cursor:pointer}.mfx-channels{display:flex;flex-direction:column;gap:8px;padding:10px}.mfx-channel{display:flex;align-items:center;gap:9px;background:#14211d;border:1px solid #1f332b;border-radius:10px;padding:10px 12px;color:#e8f4ee;font-size:13px;cursor:pointer;width:100%}.mfx-note{font-size:10.5px;color:#5c7367;text-align:center;padding:6px}.mfx-c{display:flex;flex-wrap:wrap;gap:7px;justify-content:center;padding:10px 12px;border-top:1px solid #1e2a2e;background:#0d1517}.mfx-cl{width:100%;text-align:center;font-size:10.5px;color:#7f9a8d;margin-bottom:2px}.mfx-cb{flex:1;min-width:80px;background:#13241f;border:1px solid #1f4333;color:#d7efe4;border-radius:9px;padding:8px 8px;font-size:12px;text-align:center;text-decoration:none;display:inline-block}.mfx-hero{padding:8px 14px;font-size:13.5px;color:#e8f4ee}";
  var s = document.createElement("style"); s.textContent = CSS; document.head.appendChild(s);
  var fab = document.createElement("button"); fab.className = "mfx-chat-fab"; fab.setAttribute("aria-label", "Chat");
  fab.innerHTML = '<svg viewBox="0 0 24 24"><path d="M12 3C7 3 3 7.03 3 12c0 2 .7 3.8 1.9 5.2L3 21l4-1.5c1.3.7 2.8 1 4 1 5 0 9-4 9-8.5S17 3 12 3z"/></svg>';
  document.body.appendChild(fab);
  var pan = document.createElement("div"); pan.className = "mfx-chat-panel";
  pan.innerHTML = '<div class="mfx-chat-head"><span class="dot"></span><span><b>MINDFAX OPS</b><span class="sub">AI assistant · online</span></span></div><div class="mfx-hero">Chat with us 👇</div><div class="mfx-log" id="mfxLog"></div><div class="mfx-bar"><input id="mfxInput" placeholder="Type…"/><button id="mfxSend">Send</button></div><div class="mfx-c"><div class="mfx-cl">Reach us too:</div><a class="mfx-cb" href="https://' + B + '" target="_blank" rel="noopener">💬 Telegram</a><a class="mfx-cb" href="https://wa.me/' + W + '?text=Hi%20MINDFAX%20-%20from%20site" target="_blank" rel="noopener">📱 WhatsApp</a><a class="mfx-cb" href="mailto:' + E + '?subject=Contact%20-%20MINDFAX" target="_blank" rel="noopener">✉️ Email</a></div>';
  document.body.appendChild(pan);
  setTimeout(function () { try { var tgs = document.querySelectorAll(".js-tg"); tgs.forEach(function (t) { var h = t.parentElement; if (h && !h.dataset.m) { h.dataset.m = "1"; var a = document.createElement("a"); a.className = t.className; a.textContent = "WhatsApp"; a.href = "https://wa.me/" + W + "?text=Hi%20MINDFAX%20-rep%20work"; a.target = "_blank"; t.insertAdjacentElement("afterend", a); var c = document.createElement("a"); c.className = "btn btn-ghost"; c.textContent = "Email"; c.href = "mailto:" + E + "?subject=Automation"; c.target = "_blank"; a.insertAdjacentElement("afterend", c); } }); } catch (e) {} }, 400);
  var log = document.getElementById("mfxLog"), inp = document.getElementById("mfxInput"), snd = document.getElementById("mfxSend");
  var history = [], language = "", step = "language", shown = false, nm = "", ch = "", dv = "";
  function esc(t) { return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
  function push(h) { var d = document.createElement("div"); d.className = "mfx-b ai"; d.innerHTML = h; log.appendChild(d); log.scrollTop = log.scrollHeight; }
  function pus(u) { var d = document.createElement("div"); d.className = "mfx-b you"; d.textContent = u; log.appendChild(d); log.scrollTop = log.scrollHeight; }
  function buf() { var d = document.createElement("div"); d.className = "mfx-typing"; d.textContent = "…"; log.appendChild(d); return d; }
  function rnd(bs, s2) { if (!bs || !bs.length) return; var q = document.createElement("div"); q.className = "mfx-qr"; bs.forEach(function (b) { var t = String(b || "").toLowerCase(), el = document.createElement("button"); el.className = "mfx-qb"; el.textContent = b; el.addEventListener("click", function () { if (s2 === "aci_chat" && (t.indexOf("telegram") >= 0 || t.indexOf("whatsapp") >= 0 || t.indexOf("mail") >= 0 || t.indexOf("correo") >= 0)) { var mm = encodeURIComponent("Hi MINDFAX - chatted on site"); window.open(t.indexOf("telegram") >= 0 ? "https://" + B + "?text=" + mm : t.indexOf("whatsapp") >= 0 ? "https://wa.me/" + W + "?text=" + mm : "mailto:" + E + "?subject=Chat" + "%20" + "MINDFAX"); return; } send(b, s2); }); q.appendChild(el); }); log.appendChild(q); }
  function fallback(tx) { var c = document.createElement("div"); c.className = "mfx-channels"; c.innerHTML = '<div class="tl">Prefer another channel?</div><button class="mfx-channel" data-c="t">💬 Telegram</button><button class="mfx-channel" data-c="w">💬 WhatsApp</button><button class="mfx-channel" data-c="e">📧 Email</button>'; log.appendChild(c); c.onclick = function (e) { var b = e.target.closest(".mfx-channel"); if (!b) return; var m = encodeURIComponent("MINDFAX: " + tx); window.open(b.getAttribute("data-c") === "t" ? "https://" + B + "?text=" + m : b.getAttribute("data-c") === "w" ? "https://wa.me/" + W + "?text=" + m : "mailto:" + E); }; }
  function send(tx, s2) { tx = (tx || "").trim(); if (!tx) return; if (s2 === undefined) s2 = step; if (s2 === "c_name") nm = tx; if (s2 === "c_channel") { var v = tx.toLowerCase(); ch = v.indexOf("whatsapp") >= 0 ? "WhatsApp" : v.indexOf("telegram") >= 0 ? "Telegram" : "E-mail"; } if (s2 === "c_value") dv = tx; pus(tx); history.push({ role: "user", text: tx }); var ty = buf(); var cs = step; fetch(C, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: tx, history: history.slice(0, -1), step: s2, language: language, contact: { nome: nm, canal: ch, dado: dv } }) }).then(function (r) { return r.json(); }).then(function (j) { ty.remove(); if (j.ok) { if (j.language && s2 === "language") language = j.language; if (j.step) cs = j.step; push(esc(j.reply || "").replace(/\n/g, "<br>")); history.push({ role: "assistant", text: j.reply || "" }); rnd(j.bottons, j.botStep || cs); step = cs; } else { push("Trouble replying - another channel:"); fallback(tx); } }).catch(function () { ty.remove(); push("Instability - try a channel:"); fallback(tx); }); }
  fab.addEventListener("click", function () { pan.classList.toggle("open"); if (pan.classList.contains("open") && !shown) { shown = true; step = "language"; push(esc(GREETING).replace(/\n/g, "<br>")); var q = document.createElement("div"); q.className = "mfx-qr"; LB.forEach(function (b) { var el = document.createElement("button"); el.className = "mfx-qb"; el.textContent = b; el.onclick = function () { send(b, "language"); }; q.appendChild(el); }); log.appendChild(q); setTimeout(function () { inp.focus(); }, 200); } });
  snd.addEventListener("click", function () { var v = inp.value.trim(); if (!v) return; inp.value = ""; send(v); });
  inp.addEventListener("keydown", function (e) { if (e.key === "Enter") snd.click(); });
})();
